// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeghxrrzyzludlydgpjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlZ2h4cnJ6eXpsdWRseWRncGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODUwNDUsImV4cCI6MjA2MTA2MTA0NX0.Oevajnlxq6W_kGEosWe0eDc2uuVXVwW5HpCxUY46ckc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);